<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0;net11.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.5</Version>
    <RootNamespace>Baksteen.Extensions.DeepCopy</RootNamespace>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>clone;deepclone;copy;deepcopy;reflection;extension</PackageTags>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>jpmikkers</Authors>
    <Description>Small but effective deep copy extension using object reflection. 
It has various optimizations so it remains surprisingly fast, about 7 times faster than the usual binary serialization/deserialization trick.</Description>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/jpmikkers/Baksteen.Extensions.DeepCopy.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/jpmikkers/Baksteen.Extensions.DeepCopy</PackageProjectUrl>
    <PackageReleaseNotes>Added net10 support, removed net6. Support Int128 and UInt128.</PackageReleaseNotes>
    <Copyright>Copyright (c) JPMikkers 2025</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
